apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-oauth2-proxy

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: oauth2-proxy
    path: ./deployment-patch.yaml
