apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cloudflare-tunnel
      app.kubernetes.io/version: "2024.8.3"
      app.kubernetes.io/managed-by: kustomize

images:
  - name: cloudflare/cloudflared
    newTag: "2024.8.3"
