apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: cloudflare-tunnel
    app.kubernetes.io/version: "2024.8.3"
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "",
      "TunnelID": "",
      "TunnelSecret": ""
    }
