apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apiserver
  name: apiserver
spec:
  ports:
    - name: "8008"
      port: 8008
      targetPort: 8008
  selector:
    io.kompose.service: apiserver
