apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-clearml

resources:
  - ../../base

labels:
  - pairs:
      environment: development

patches:
  - target:
      kind: Deployment
      name: auth-gateway
    path: ./deployment-patch.yaml
