apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-keycloak

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: keycloak-config
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: keycloak

labels:
  - pairs:
      environment: development
