apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    io.kompose.service: mongo # match với label trong Deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
