apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: mlops
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
  KC_DB_USERNAME: keycloak
  KC_DB_PASSWORD: keycloak
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  KC_HOSTNAME: localhost
  KC_HOSTNAME_ADMIN: localhost
  KC_PROXY: edge
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_MANAGEMENT_ENABLED: "true"
  KC_HTTP_MANAGEMENT_PORT: "9000"
  KC_HEALTH_ENABLED: "true"
  POSTGRES_DB: keycloak
  POSTGRES_PASSWORD: keycloak
  POSTGRES_USER: keycloak
