apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app.kubernetes.io/name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak-db
    spec:
      containers:
        - name: postgres
          image: postgres:16.8
          envFrom:
            - configMapRef:
                name: keycloak-config
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: keycloak-db-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
                - -d
                - keycloak
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
                - -d
                - keycloak
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: keycloak-db-data
          persistentVolumeClaim:
            claimName: keycloak-db-data
