apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  labels:
    app.kubernetes.io/name: keycloak-db
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak-db
  type: ClusterIP
