apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-data
  labels:
    app.kubernetes.io/name: keycloak-db
    app.kubernetes.io/part-of: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
