apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-cloudflare-tunnel
spec:
  template:
    spec:
      containers:
        - name: cloudflare-tunnel
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
