apiVersion: v1
kind: Secret
metadata:
  name: dev-cloudflare-tunnel
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "fd22145188a5cea5847e7540201e8a0f",
      "TunnelID": "7ca7c9a9-5c23-43dc-ad77-f204cb7dd328",
      "TunnelSecret": "v+5ziwWC3jlklc0Yb/4IsKp6q17Oq6Qu+AFNIHAJbPk="
    }
