apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: auth-gateway
      app.kubernetes.io/name: auth-gateway
      app.kubernetes.io/component: auth-gateway
