apiVersion: v1
kind: Service
metadata:
  name: auth-gateway
  labels:
    app.kubernetes.io/name: auth-gateway
    app.kubernetes.io/component: auth-gateway
spec:
  selector:
    app.kubernetes.io/name: auth-gateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
