apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc-data.yaml
  - pvc-logs.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: clearml
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/component: database
