apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-services
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: clearml-agent-services
          env:
            - name: CLEARML_AGENT_QUEUE
              value: train
      volumes:
        - name: agent-config
          persistentVolumeClaim:
            claimName: agent-config-train
