apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-ingress-controller

resources:
  - ../../base
  - ingress-dynamic.yaml

patches:
  - target:
      kind: Deployment
      name: traefik
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
