apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-minio-operator
resources:
- ../../base
patches:
  - path: operator-patch.yaml
    target:
      kind: Deployment
      name: minio-operator
